### ISSUE TITLE
Corrigir versão fixada do provider hashicorp/google no versions.tf

### ISSUE THREAD

**Issue by snifbr** [mentoriaiac/iac-modulo-rede-gcp#6]
https://github.com/mentoriaiac/iac-modulo-rede-gcp/blob/466f98aa1d627b6a69cb45e853763d81e6d1ba6a/versions.tf#L6

### Descrição do problema

Foi fixada a versão do provider hashicorp/google na versão 3.73.0 no arquivo `versions.tf` e isto quebra o `terraform init` nos módulos que consomem este módulo terraform.

**sugestão** : alterar para `version = ">= 3.73.0"` ou remover linha.

**Comment by Rehzende** [comment]
a ideia  de fixar a versão é para ter segurança no modulo, pois se a versão nova do provider remover algum atributo o modulo irá quebrar.

**Comment by snifbr** [comment]
Valeu pelo retorno @Rehzende , vou repassar para a turma que está ajudando no módulo do iac-modulo-groundwork a informação.
